version: '3'
services:
  client:
    platform: linux/arm64/v8
    image: sn_client_prod
    build:
      dockerfile: Dockerfile.prod
    container_name: sn_client_prod
    env_file:
      - ./client/.env.production
    ports:
      - "8010:80"

  server:
    platform: linux/arm64/v8
    image: sn_server_prod
    build:
      dockerfile: Dockerfile.prod
    container_name: sn_server_prod
    env_file:
      - ./server/.prod.env
    ports:
      - '8000:80'

  db:
    platform: linux/arm64/v8
    container_name: sn_db_prod
    env_file:
      - ./database/.prod.env
    volumes:
      - database_prod:/var/lib/mysql

volumes:
  database_prod: