version: '3'
services:
  # Create client container
  client: # Name of our service
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - '8010:8010' # Bind port 8010 of host to 8010 of container
    container_name: client
    restart: always # What to do if container crashes
    links:
      - server
    # depends_on:
    #   server:
    #     condition: service_healthy
  # Create server container
  server:
    build: ./server
    ports:
      - '8000:8000'
    container_name: server
    restart: always
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  # Create database container
  db:
    image: mysql
    ports:
      - '8306:8306'
    container_name: database
    restart: always
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/dump.sql
    # Set environment variables
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: social_network
    #   MYSQL_USER: social_network_backend
    #   MYSQL_PASSWORD: social_network_backend
    env_file:
      - ./database/.env
    healthcheck:
      # runs on port 8306
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "8306"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  default:
    name: social_network
