version: '3'
services:
  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    restart: always
    links:
      - server

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    links:
      - db
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    env_file:
      - ./database/.env
    restart: always
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --port=$$MYSQL_TCP_PORT -e 'SHOW DATABASES;'
      interval: 30s
      timeout: 10s
      retries: 3
