# Base image
FROM node
# Make folder to put our files in
RUN mkdir -p /usr/src/social-network
RUN mkdir -p /usr/src/social-network/server
# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/social-network/server
# Copy package json and install dependencies
COPY package*.json ./
RUN npm install
# Copy our app
COPY . .
# Expose port to access server
EXPOSE 8000
# Command to run our app
CMD [ "npm", "run", "live"]